### ISSUE TITLE
how to install on nixos

### ISSUE THREAD

**Issue by DieracDelta** [justinbarclay/parinfer-rust-mode#2]
I'm really keen to try this out but I'm on nixos. Has anyone got this working on nixos? I'm doing my configuration for emacs through home-manager and I'm struggling to see how I would follow option 1 or 2 listed in the readme to install this from a nixos config file.

**Comment by DieracDelta** [comment]
To follow up on this, I was "successfully" able to get access to all three modes using nix. A couple of things jumped out at me while I was doing this:

- The documentation was confusing to me. There seemed like two separate install options, but you really either need to do both options #1 and #2 to build a nix package around it. I realize that the program does offer to download for you but if you're trying to set things up at compile time this becomes infeasible to give input from stdin.
- The version used by the program is out of date. The most recent version of the library is `0.4.3` now, not `0.4.0`. Things still seem to work just fine when I bump the version (though I haven't figured out how to run the tests).
- To run this on NixOS I did two things--created an overlay that is essentially the `parinfer-rust` nixos package but without the postinstall kakoune script portion; this probably isn't necessary but I wanted the extra versatility and I didn't want to install kakoune. I also needed to create an emacs package, which was just a trivialBuild wrapper that feeds in the path to the `.so` library on the `LD_LOADER_PATH`. The issue then just became finding the file on that path. I wrote an emacs lisp function to do this, and it works if I open emacs and execute the files. But right now I can't seem to get the package to compile ahead of time as a nix package with a custom function, as the package just isn't able to find it. I've got this sitting over on my fork right now. The only way I can get it to compile ahead of time is to hardcode in the path to the installed library directly into the `require 'parinfer-rust` statement. I'm really confused about the discrepency here.

I'll see if I can pull together a PR that at least bumps the version.

**Comment by justinbarclay** [comment]
Hey, thanks for the feedback. 

1. You're right I think Option #1 and Option #2 _are_ confusing. I think where I intended the divide to be is between compiling the rust library or having `parinfer-rust-mode` download the library from the [`parinfer-rust`](https://github.com/eraserhd/parinfer-rust/releases/tag/v0.4.3) repo for you. I will update the docs tomorrow to reflect this.

 Would it help if I added in a package var to allow you to set the for you, thus being able to always download that file and overcome the need to stdin (this should be trivial to add)?

2. I have added a [branch ](https://github.com/justinbarclay/parinfer-rust-mode/tree/update-versions)for using/requiring the newest (0.4.3) version of parinfer-rust. In addition, I'll also update the docs for how to run tests for this project. If you want to run tests from the command line you will need to have [cask](https://github.com/cask/cask) installed. Then, you'll need to set an environment variable and then you can use the Makefile to run the test: 
```
$ export parinfer_rust_test=true
$ make test
```

3. I am not sure how much I can help with nixOS, as I am very unfamiliar with that. But IIRC for dynamic modules, which the rust library is, we need to be explicit in loading the module before parinfer-rust can run. More on this can be found here: https://phst.eu/emacs-modules.html#module-loading-and-initialization
That's why I think I pass in the location of the module in the require function. If you don't want to use the require function to load the module, you'll need to call `module-load` and then `require`.

**Comment by DieracDelta** [comment]
Thanks for the quick response! A couple of things:
- I've installed cask, and ran the tests. I get a couple of failures:
```
Ran 143 tests in 1.386 seconds
13 unexpected results:
   FAILED  parinfer-paren-30
   FAILED  parinfer-paren-35
   FAILED  parinfer-paren-36
   FAILED  parinfer-paren-38
   FAILED  parinfer-smart-12
   FAILED  parinfer-smart-13
   FAILED  parinfer-smart-18
   FAILED  parinfer-smart-20
   FAILED  parinfer-smart-25
   FAILED  parinfer-smart-26
   FAILED  parinfer-smart-28
   FAILED  parinfer-smart-30
   FAILED  parinfer-smart-33
```
- I've tested the smart mode. I'm also using evil mode, and there's this odd issue where when I go up or down (`evil-next/previous-visual-line`), some lines become more indented. Other than that, as far as I can tell, things work as expected.

**Comment by DieracDelta** [comment]
Actually, I'd like to update this a bit. In order for me to get parinfer-rust-mode to allow itself to be activated, I had to do something like:
```
(setq max-lisp-eval-depth 99999)                                     
(setq max-specpdl-size 99999)
```
Then, when I enable parinfer-rust-mode, my emacsclient crashes, and I have to reconnect. All my buffers are deleted but now when I enable parinfer-rust-mode, it works as expected. Pretty odd and feels like a buffer overflow or something. Will investigate further.

**Comment by justinbarclay** [comment]
1. Getting tests to pass, this definitely looks to be an issue with `PARINFER_RUST_TEST` not being set properly. Since you forked I did some updating to the codebase. One of those changes was preferring upper cased env vars, as can be seen [here](https://github.com/justinbarclay/parinfer-rust-mode/commit/fd6dc538c8d110a39dc67429c2987407d2ffabb2).
So if you don't want to rebase my changes in than you would need to use `parinfer_rust_test=true make test`.
However, the two other major updates were slightly better tracking when inside undo and updating to the latest parinfer-rust version.

2. Is this a consistent behviour when use `evil-next/previous-line` that it reformats your code? As in does this happen every time, or only sometimes? If only sometimes is it reformatting to syntactically incorrect code?
How does parinfer behave when you try similar operations on that sexp when run in the parinfer reference environment: https://shaunlebron.github.io/parinfer/demo?

I ask these questions because parinfer is fairly opinionated about layout and could add or remove whitespace as it sees fit.

3. 
a. Needing to set `max-lisp-eval-depth` and `max-specpdl-size` is really weird as it's not behavior I have experience on Emacs 26+ on MacOs, or ArchLinux, or in my [test environments](https://github.com/Silex/docker-emacs).
b. Yeah unfortunately `parinfer-rust-mode` can still crash Emacs (which is why I haven't pulled this out of Alpha). It generally only has happened to me when I try to do some undo operations after I've gotten my code into a bad shape, so it crashing Emacs when you first enable it is weird. May I ask what modes you auto-enable it for?

I would be careful about running it in all emacs-lisp files, particularly when loading libraries. I know I've run into issues where some authors write functions in a non standard way that caused their package to break when `smart-mode` corrected it. I've switched `parinfer-rust-mode` from running on a load hook for elisp to only loading when activate `parinfer-rust-mode`

**Comment by DieracDelta** [comment]
1) Thanks for updating the documentation/versioning; I appreciate your responsiveness here! I've rebased ontop of your pushed code and now all the tests pass. In response to your question about the package variable--that would be super helpful in automating the build on nix.

2) I'll get back to you about this with a sexp and a specific set of actions soon.

3) I'm using emacs 28 (rev `46d8973e4ecbcfa39c4657ef14a54a6eacf761a5`, so about about a week behind the emacs master branch right now). The behavior is really odd. The example I gave earlier was only for emacs running as a daemon. When I run emacs as a standalone application (not as a daemon) on the following input, it causes emacs to segfault with a bus error (without having to set those variables):

```emacs
M-x switch-to-buffer
new-buffer
M-x parinfer-rust-mode
```
This yields the following output:
```
Fatal error 11: Segmentation fault
[1]    30621 bus error (core dumped)  emacs
```
Note that for this, the way I am loading the file right now is:
```(use-package parinfer-rust-mode                                       
:hook (lisp-mode . 'parinfer-rust-mode)                             
:init
(setq max-lisp-eval-depth 99999)
(setq max-specpdl-size 99999)                                                               
(module-load                                                        
"/nix/store/xdbkvlm537iglj6rx8f0sjli9afbjyn1-parinfer-rust-mode-overlay-0.4.3/lib/libparinfer_rust.so")                               
(setq parinfer-rust-library "/nix/store/xdbkvlm537iglj6rx8f0sjli9afbjyn1-parinfer-rust-mode-overlay-0.4.3/lib/libparinfer_rust.so"))```

I haven't enabled hooks for any mode yet (although, I'd like to add hooks for any sort of lisp).

I know that my usecase is a bit contrived (and perhaps I should downgrade emacs to something more stable). That being said, is your test build successful on the master environment you linked to? If so, then this segfault is probably an error on my end that's nix related.

**Comment by justinbarclay** [comment]
1. I've added a new variable `parinfer-rust--auto-download-p` that _should_ be set-up to automatically download the library, using curl, from github for you and load it into emacs before/at the same time as loading parinfer-rust-mode.
I talk about it [here](https://github.com/justinbarclay/parinfer-rust-mode#option-1-let-parinfer-rust-install-it-for-you). But the short of it is `(setq parinfer-rust--auto-download-p 't)` turns the feature on.

3. I just checked and the master version of Emacs in [docker-emacs](https://github.com/Silex/docker-emacs) and it is running on commit `3a7894ecd11c66337e7aea8ade8f47673d290a24`. It can load the parinfer-rust-mode and library (without needing to set `max-lisp-eval-depth` or `max-specpdl-size`).
If you have docker installed yourself, you could clone this repo (or go to wherver your fork exists) and starting in your shell run: 
1. docker run --rm -it -v $(pwd):/tmp/parinfer-rust-mode silex/emacs:master-dev sh
2. In the docker shell run `emacs -L /tmp/parinfer-rust-mode`
3. In the emacs scratch buffer,:
``` elisp
(require 'parinfer-rust-mode)  ;; say yes when it prompts you to download the library.
(parinfer-rust-mode)
```
4. Start writing lisp as normal.

https://imgur.com/a/Hdei04R

**Comment by justinbarclay** [comment]
Hi @DieracDelte,

I've changed the variable name and added it to the [documentation](https://github.com/justinbarclay/parinfer-rust-mode#customizations).

I'm going to close this issue as it's been silent for the last month, but I'm willing to reopen it if there are anymore issues with getting this working on NixOS.

Additionally, if you think there are special instructions needed for install on NixOS, I'd love to hear about them, so I can add it to my documentation. :)
